apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-sentinel.fullname" . }}-api
  labels:
    {{- include "tech-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tech-sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
