apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tech-sentinel.fullname" . }}-config
  labels:
    {{- include "tech-sentinel.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  TS_API_PORT: {{ .Values.service.api.port | quote }}
  TS_STATUS_PORT: {{ .Values.service.statusPage.port | quote }}
  TS_PROBE_INTERVAL_SECONDS: {{ .Values.config.probeInterval | quote }}
  TS_PROBE_CONCURRENCY: {{ .Values.config.probeConcurrency | quote }}
  TS_PROBE_TIMEOUT_SECONDS: {{ .Values.config.probeTimeout | quote }}
  TS_ALERT_CONSECUTIVE_FAILURES: {{ .Values.config.alertConsecutiveFailures | quote }}
  TS_JWT_EXPIRE_MINUTES: {{ .Values.config.jwtExpireMinutes | quote }}
  TS_CONTROL_PLANE_URL: "http://{{ include "tech-sentinel.fullname" . }}-api:{{ .Values.service.api.port }}"
