apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-sentinel.fullname" . }}-secrets
  labels:
    {{- include "tech-sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.database.password | default "changeme" }}"
  TS_JWT_SECRET: "{{ .Values.config.jwtSecret | default "changeme" }}"
  TS_API_KEY: "{{ .Values.config.apiKey | default "changeme" }}"
