apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-sentinel.fullname" . | quote }}-secrets
  labels:
{{ include "tech-sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | default "changeme" | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | default "changeme" | quote }}
  TS_JWT_SECRET: {{ .Values.config.jwtSecret | default "changeme" | quote }}
  TS_API_KEY: {{ .Values.config.apiKey | default "changeme" | quote }}
